export enum Block {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  COBBLESTONE = 4,
  BEDROCK = 5,
  OAK_LOG = 6,
  OAK_LEAVES = 7,
  OAK_PLANKS = 8,
  BIRCH_LOG = 9,
  BIRCH_LEAVES = 10,
  BIRCH_PLANKS = 11,
  SAND = 12,
  SANDSTONE = 13,
  GRAVEL = 14,
  GLASS = 15,
  WATER = 16,
  COAL_ORE = 17,
  IRON_ORE = 18,
  GOLD_ORE = 19,
  DIAMOND_ORE = 20,
  REDSTONE_ORE = 21,
  CRAFTING_TABLE = 22,
  FURNACE = 23,
  CHEST = 24,
  BRICKS = 25,
  BOOKSHELF = 26,
  TNT = 27,
  TORCH = 28,
  DANDELION = 29,
  POPPY = 30,
  SNOW = 31,
  CACTUS = 32,
  WHEAT_CROP = 33,
  BED = 34,
  OBSIDIAN = 35,
  PORTAL = 36,
  NETHERRACK = 37,
  SOUL_SAND = 38,
  GLOWSTONE = 39,
  NETHER_BRICKS = 40,
  NETHER_QUARTZ_ORE = 41,
  LAVA = 42,
  ENCHANTING_TABLE = 43,
  BREWING_STAND = 44,
  NETHER_WART_BLOCK = 45,
  CORAL_BRAIN = 48,
  CORAL_BUBBLE = 49,
  CORAL_FIRE = 50,
  CORAL_HORN = 51,
  CORAL_TUBE = 52,
  SEAGRASS = 53,
  KELP = 54,
  SEA_LANTERN = 55,
  REDSTONE_WIRE = 56,
  REDSTONE_TORCH = 57,
  LEVER = 58,
  REDSTONE_LAMP = 59,
  REDSTONE_LAMP_LIT = 60,
  FARMLAND = 61,
  COBWEB = 62,
  RAIL = 63,
  SUGAR_CANE = 64,
  RED_MUSHROOM = 65,
  BROWN_MUSHROOM = 66,
  LILY_PAD = 67,
  OAK_FENCE = 68,
  DRIPSTONE_BLOCK = 69,
  ICE = 70,
  NETHER_BRICK_FENCE = 71,
  SPAWNER = 72,
  END_STONE = 73,
  END_PORTAL_FRAME = 74,
  END_PORTAL = 75,
  END_CRYSTAL = 76,
  END_PORTAL_FRAME_FILLED = 77
}

export enum ItemId {
  STICK = 101,
  WOODEN_PICKAXE = 102,
  STONE_PICKAXE = 103,
  IRON_PICKAXE = 104,
  DIAMOND_PICKAXE = 105,
  WOODEN_SWORD = 106,
  STONE_SWORD = 107,
  IRON_SWORD = 108,
  DIAMOND_SWORD = 109,
  WOODEN_AXE = 110,
  STONE_AXE = 111,
  IRON_AXE = 112,
  DIAMOND_AXE = 113,
  WOODEN_SHOVEL = 114,
  STONE_SHOVEL = 115,
  IRON_SHOVEL = 116,
  DIAMOND_SHOVEL = 117,
  COAL = 118,
  IRON_INGOT = 119,
  GOLD_INGOT = 120,
  DIAMOND = 121,
  APPLE = 122,
  EMERALD = 123,
  BREAD = 124,
  RAW_BEEF = 125,
  COOKED_BEEF = 126,
  PORKCHOP = 127,
  FEATHER = 128,
  RAW_CHICKEN = 129,
  LEATHER = 130,
  GUNPOWDER = 131,
  ROTTEN_FLESH = 132,
  WOOL = 133,
  WHEAT = 134,
  BOW = 135,
  ARROW = 136,
  BONE = 137,
  FLINT = 138,
  IRON_HELMET = 139,
  IRON_CHESTPLATE = 140,
  IRON_LEGGINGS = 141,
  IRON_BOOTS = 142,
  DIAMOND_HELMET = 143,
  DIAMOND_CHESTPLATE = 144,
  DIAMOND_LEGGINGS = 145,
  DIAMOND_BOOTS = 146,
  QUARTZ = 147,
  GLOWSTONE_DUST = 148,
  BOOK = 149,
  GOLD_NUGGET = 150,
  GHAST_TEAR = 151,
  BLAZE_ROD = 152,
  BLAZE_POWDER = 153,
  NETHER_WART = 154,
  GLASS_BOTTLE = 155,
  POTION_HEALING = 156,
  POTION_SPEED = 157,
  POTION_FIRE_RESISTANCE = 158,
  POTION_NIGHT_VISION = 159,
  POTION_STRENGTH = 160,
  RAW_FISH = 161,
  COOKED_FISH = 162,
  REDSTONE_DUST = 163,
  LAPIS_LAZULI = 164,
  BUCKET = 165,
  WATER_BUCKET = 166,
  LAVA_BUCKET = 167,
  MILK_BUCKET = 168,
  WHEAT_SEEDS = 169,
  WOODEN_HOE = 170,
  STONE_HOE = 171,
  IRON_HOE = 172,
  DIAMOND_HOE = 173,
  BOAT = 174,
  MINECART = 175,
  ENDER_PEARL = 176,
  EYE_OF_ENDER = 177,
  LEATHER_HELMET = 178,
  LEATHER_CHESTPLATE = 179,
  LEATHER_LEGGINGS = 180,
  LEATHER_BOOTS = 181,
  GOLDEN_HELMET = 182,
  GOLDEN_CHESTPLATE = 183,
  GOLDEN_LEGGINGS = 184,
  GOLDEN_BOOTS = 185,
  NETHERITE_HELMET = 186,
  NETHERITE_CHESTPLATE = 187,
  NETHERITE_LEGGINGS = 188,
  NETHERITE_BOOTS = 189,
  NETHERITE_INGOT = 190
}

export type SoundGroup = 'grass' | 'stone' | 'wood' | 'sand' | 'gravel' | 'glass';

export interface BlockDef {
  id: Block;
  name: string;
  solid: boolean;
  transparent: boolean;
  luminance?: number;
  hardness: number; // in seconds with bare hand
  dropId?: number;
  soundType: SoundGroup;
  // Face atlas indices: [PX, NX, PY, NY, PZ, NZ] -> [Right, Left, Top, Bottom, Front, Back]
  textures: [number, number, number, number, number, number];
}

export interface ItemDef {
  id: number;
  name: string;
  isBlock: boolean;
  maxStack: number;
  toolType?: 'pickaxe' | 'axe' | 'shovel' | 'sword';
  toolTier?: number; // 1: wood, 2: stone, 3: iron, 4: diamond
  miningSpeedMultiplier?: number;
  maxDurability?: number;
  armorSlot?: 'helmet' | 'chestplate' | 'leggings' | 'boots';
  defensePoints?: number;
}

// Atlas Texture indices (16x16 grid on 256x256 atlas = 256 tiles)
export const TextureIndex = {
  GRASS_TOP: 0,
  GRASS_SIDE: 1,
  DIRT: 2,
  STONE: 3,
  COBBLESTONE: 4,
  BEDROCK: 5,
  OAK_LOG_SIDE: 6,
  OAK_LOG_TOP: 7,
  OAK_LEAVES: 8,
  OAK_PLANKS: 9,
  BIRCH_LOG_SIDE: 10,
  BIRCH_LOG_TOP: 11,
  BIRCH_LEAVES: 12,
  BIRCH_PLANKS: 13,
  SAND: 14,
  SANDSTONE_SIDE: 15,
  SANDSTONE_TOP: 16,
  GRAVEL: 17,
  GLASS: 18,
  WATER: 19,
  COAL_ORE: 20,
  IRON_ORE: 21,
  GOLD_ORE: 22,
  DIAMOND_ORE: 23,
  REDSTONE_ORE: 24,
  CRAFTING_TABLE_TOP: 25,
  CRAFTING_TABLE_SIDE: 26,
  CRAFTING_TABLE_FRONT: 27,
  FURNACE_SIDE: 28,
  FURNACE_FRONT: 29,
  CHEST_SIDE: 30,
  CHEST_TOP: 31,
  CHEST_FRONT: 32,
  BRICKS: 33,
  BOOKSHELF: 34,
  TNT_SIDE: 35,
  TNT_TOP: 36,
  TNT_BOTTOM: 37,
  TORCH: 38,
  DANDELION: 39,
  POPPY: 40,
  SNOW: 41,
  CACTUS_SIDE: 42,
  CACTUS_TOP: 43,
  WHEAT_CROP: 44,
  BED_TOP: 45,
  BED_SIDE: 46,
  OBSIDIAN: 47,
  PORTAL: 48,
  NETHERRACK: 49,
  SOUL_SAND: 50,
  GLOWSTONE: 51,
  NETHER_BRICKS: 52,
  NETHER_QUARTZ_ORE: 53,
  LAVA: 54,
  ENCHANTING_TABLE_TOP: 55,
  ENCHANTING_TABLE_SIDE: 56,
  ENCHANTING_TABLE_BOTTOM: 57,
  BREWING_STAND_SIDE: 58,
  BREWING_STAND_TOP: 59,
  NETHER_WART_BLOCK: 60,
  CORAL_BRAIN: 61,
  CORAL_BUBBLE: 62,
  CORAL_FIRE: 63,
  CORAL_HORN: 64,
  CORAL_TUBE: 65,
  SEAGRASS: 66,
  KELP_TOP: 67,
  KELP_STEM: 68,
  SEA_LANTERN: 69,
  REDSTONE_WIRE: 70,
  REDSTONE_TORCH: 71,
  LEVER: 72,
  REDSTONE_LAMP: 73,
  REDSTONE_LAMP_LIT: 74,
  FARMLAND_TOP: 75,
  FARMLAND_SIDE: 76,
  COBWEB: 77,
  RAIL: 78,
  SUGAR_CANE: 79,
  RED_MUSHROOM: 80,
  BROWN_MUSHROOM: 81,
  LILY_PAD: 82,
  DRIPSTONE_BLOCK: 83,
  ICE: 84,
  SPAWNER: 85,
  END_STONE: 86,
  END_PORTAL_FRAME_TOP: 87,
  END_PORTAL_FRAME_SIDE: 88,
  END_PORTAL_FRAME_FILLED_TOP: 89,
  END_PORTAL: 90,
  END_CRYSTAL: 91
};

export const BLOCK_DEFS: Record<number, BlockDef> = {
  [Block.AIR]: {
    id: Block.AIR,
    name: 'Air',
    solid: false,
    transparent: true,
    hardness: 0,
    soundType: 'grass',
    textures: [0, 0, 0, 0, 0, 0]
  },
  [Block.GRASS]: {
    id: Block.GRASS,
    name: 'Grass Block',
    solid: true,
    transparent: false,
    hardness: 0.6,
    dropId: Block.DIRT,
    soundType: 'grass',
    // [PX, NX, PY, NY, PZ, NZ]
    textures: [
      TextureIndex.GRASS_SIDE,
      TextureIndex.GRASS_SIDE,
      TextureIndex.GRASS_TOP,
      TextureIndex.DIRT,
      TextureIndex.GRASS_SIDE,
      TextureIndex.GRASS_SIDE
    ]
  },
  [Block.DIRT]: {
    id: Block.DIRT,
    name: 'Dirt',
    solid: true,
    transparent: false,
    hardness: 0.5,
    dropId: Block.DIRT,
    soundType: 'gravel',
    textures: [TextureIndex.DIRT, TextureIndex.DIRT, TextureIndex.DIRT, TextureIndex.DIRT, TextureIndex.DIRT, TextureIndex.DIRT]
  },
  [Block.STONE]: {
    id: Block.STONE,
    name: 'Stone',
    solid: true,
    transparent: false,
    hardness: 1.5,
    dropId: Block.COBBLESTONE,
    soundType: 'stone',
    textures: [TextureIndex.STONE, TextureIndex.STONE, TextureIndex.STONE, TextureIndex.STONE, TextureIndex.STONE, TextureIndex.STONE]
  },
  [Block.COBBLESTONE]: {
    id: Block.COBBLESTONE,
    name: 'Cobblestone',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.COBBLESTONE,
    soundType: 'stone',
    textures: [TextureIndex.COBBLESTONE, TextureIndex.COBBLESTONE, TextureIndex.COBBLESTONE, TextureIndex.COBBLESTONE, TextureIndex.COBBLESTONE, TextureIndex.COBBLESTONE]
  },
  [Block.BEDROCK]: {
    id: Block.BEDROCK,
    name: 'Bedrock',
    solid: true,
    transparent: false,
    hardness: Infinity,
    soundType: 'stone',
    textures: [TextureIndex.BEDROCK, TextureIndex.BEDROCK, TextureIndex.BEDROCK, TextureIndex.BEDROCK, TextureIndex.BEDROCK, TextureIndex.BEDROCK]
  },
  [Block.OAK_LOG]: {
    id: Block.OAK_LOG,
    name: 'Oak Log',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.OAK_LOG,
    soundType: 'wood',
    textures: [
      TextureIndex.OAK_LOG_SIDE,
      TextureIndex.OAK_LOG_SIDE,
      TextureIndex.OAK_LOG_TOP,
      TextureIndex.OAK_LOG_TOP,
      TextureIndex.OAK_LOG_SIDE,
      TextureIndex.OAK_LOG_SIDE
    ]
  },
  [Block.OAK_LEAVES]: {
    id: Block.OAK_LEAVES,
    name: 'Oak Leaves',
    solid: true,
    transparent: true,
    hardness: 0.2,
    dropId: ItemId.APPLE,
    soundType: 'grass',
    textures: [TextureIndex.OAK_LEAVES, TextureIndex.OAK_LEAVES, TextureIndex.OAK_LEAVES, TextureIndex.OAK_LEAVES, TextureIndex.OAK_LEAVES, TextureIndex.OAK_LEAVES]
  },
  [Block.OAK_PLANKS]: {
    id: Block.OAK_PLANKS,
    name: 'Oak Planks',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.OAK_PLANKS,
    soundType: 'wood',
    textures: [TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS]
  },
  [Block.BIRCH_LOG]: {
    id: Block.BIRCH_LOG,
    name: 'Birch Log',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.BIRCH_LOG,
    soundType: 'wood',
    textures: [
      TextureIndex.BIRCH_LOG_SIDE,
      TextureIndex.BIRCH_LOG_SIDE,
      TextureIndex.BIRCH_LOG_TOP,
      TextureIndex.BIRCH_LOG_TOP,
      TextureIndex.BIRCH_LOG_SIDE,
      TextureIndex.BIRCH_LOG_SIDE
    ]
  },
  [Block.BIRCH_LEAVES]: {
    id: Block.BIRCH_LEAVES,
    name: 'Birch Leaves',
    solid: true,
    transparent: true,
    hardness: 0.2,
    soundType: 'grass',
    textures: [TextureIndex.BIRCH_LEAVES, TextureIndex.BIRCH_LEAVES, TextureIndex.BIRCH_LEAVES, TextureIndex.BIRCH_LEAVES, TextureIndex.BIRCH_LEAVES, TextureIndex.BIRCH_LEAVES]
  },
  [Block.BIRCH_PLANKS]: {
    id: Block.BIRCH_PLANKS,
    name: 'Birch Planks',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.BIRCH_PLANKS,
    soundType: 'wood',
    textures: [TextureIndex.BIRCH_PLANKS, TextureIndex.BIRCH_PLANKS, TextureIndex.BIRCH_PLANKS, TextureIndex.BIRCH_PLANKS, TextureIndex.BIRCH_PLANKS, TextureIndex.BIRCH_PLANKS]
  },
  [Block.SAND]: {
    id: Block.SAND,
    name: 'Sand',
    solid: true,
    transparent: false,
    hardness: 0.5,
    dropId: Block.SAND,
    soundType: 'sand',
    textures: [TextureIndex.SAND, TextureIndex.SAND, TextureIndex.SAND, TextureIndex.SAND, TextureIndex.SAND, TextureIndex.SAND]
  },
  [Block.SANDSTONE]: {
    id: Block.SANDSTONE,
    name: 'Sandstone',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.SANDSTONE,
    soundType: 'stone',
    textures: [
      TextureIndex.SANDSTONE_SIDE,
      TextureIndex.SANDSTONE_SIDE,
      TextureIndex.SANDSTONE_TOP,
      TextureIndex.SANDSTONE_SIDE,
      TextureIndex.SANDSTONE_SIDE,
      TextureIndex.SANDSTONE_SIDE
    ]
  },
  [Block.GRAVEL]: {
    id: Block.GRAVEL,
    name: 'Gravel',
    solid: true,
    transparent: false,
    hardness: 0.6,
    dropId: Block.GRAVEL,
    soundType: 'gravel',
    textures: [TextureIndex.GRAVEL, TextureIndex.GRAVEL, TextureIndex.GRAVEL, TextureIndex.GRAVEL, TextureIndex.GRAVEL, TextureIndex.GRAVEL]
  },
  [Block.GLASS]: {
    id: Block.GLASS,
    name: 'Glass',
    solid: true,
    transparent: true,
    hardness: 0.3,
    soundType: 'glass',
    textures: [TextureIndex.GLASS, TextureIndex.GLASS, TextureIndex.GLASS, TextureIndex.GLASS, TextureIndex.GLASS, TextureIndex.GLASS]
  },
  [Block.WATER]: {
    id: Block.WATER,
    name: 'Water',
    solid: false,
    transparent: true,
    hardness: Infinity,
    soundType: 'sand',
    textures: [TextureIndex.WATER, TextureIndex.WATER, TextureIndex.WATER, TextureIndex.WATER, TextureIndex.WATER, TextureIndex.WATER]
  },
  [Block.COAL_ORE]: {
    id: Block.COAL_ORE,
    name: 'Coal Ore',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: ItemId.COAL,
    soundType: 'stone',
    textures: [TextureIndex.COAL_ORE, TextureIndex.COAL_ORE, TextureIndex.COAL_ORE, TextureIndex.COAL_ORE, TextureIndex.COAL_ORE, TextureIndex.COAL_ORE]
  },
  [Block.IRON_ORE]: {
    id: Block.IRON_ORE,
    name: 'Iron Ore',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: ItemId.IRON_INGOT,
    soundType: 'stone',
    textures: [TextureIndex.IRON_ORE, TextureIndex.IRON_ORE, TextureIndex.IRON_ORE, TextureIndex.IRON_ORE, TextureIndex.IRON_ORE, TextureIndex.IRON_ORE]
  },
  [Block.GOLD_ORE]: {
    id: Block.GOLD_ORE,
    name: 'Gold Ore',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: ItemId.GOLD_INGOT,
    soundType: 'stone',
    textures: [TextureIndex.GOLD_ORE, TextureIndex.GOLD_ORE, TextureIndex.GOLD_ORE, TextureIndex.GOLD_ORE, TextureIndex.GOLD_ORE, TextureIndex.GOLD_ORE]
  },
  [Block.DIAMOND_ORE]: {
    id: Block.DIAMOND_ORE,
    name: 'Diamond Ore',
    solid: true,
    transparent: false,
    hardness: 3.5,
    dropId: ItemId.DIAMOND,
    soundType: 'stone',
    textures: [TextureIndex.DIAMOND_ORE, TextureIndex.DIAMOND_ORE, TextureIndex.DIAMOND_ORE, TextureIndex.DIAMOND_ORE, TextureIndex.DIAMOND_ORE, TextureIndex.DIAMOND_ORE]
  },
  [Block.REDSTONE_ORE]: {
    id: Block.REDSTONE_ORE,
    name: 'Redstone Ore',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: ItemId.REDSTONE_DUST,
    luminance: 9,
    soundType: 'stone',
    textures: [TextureIndex.REDSTONE_ORE, TextureIndex.REDSTONE_ORE, TextureIndex.REDSTONE_ORE, TextureIndex.REDSTONE_ORE, TextureIndex.REDSTONE_ORE, TextureIndex.REDSTONE_ORE]
  },
  [Block.CRAFTING_TABLE]: {
    id: Block.CRAFTING_TABLE,
    name: 'Crafting Table',
    solid: true,
    transparent: false,
    hardness: 2.5,
    dropId: Block.CRAFTING_TABLE,
    soundType: 'wood',
    textures: [
      TextureIndex.CRAFTING_TABLE_SIDE,
      TextureIndex.CRAFTING_TABLE_SIDE,
      TextureIndex.CRAFTING_TABLE_TOP,
      TextureIndex.OAK_PLANKS,
      TextureIndex.CRAFTING_TABLE_FRONT,
      TextureIndex.CRAFTING_TABLE_SIDE
    ]
  },
  [Block.FURNACE]: {
    id: Block.FURNACE,
    name: 'Furnace',
    solid: true,
    transparent: false,
    hardness: 3.5,
    dropId: Block.FURNACE,
    soundType: 'stone',
    textures: [
      TextureIndex.FURNACE_SIDE,
      TextureIndex.FURNACE_SIDE,
      TextureIndex.STONE,
      TextureIndex.STONE,
      TextureIndex.FURNACE_FRONT,
      TextureIndex.FURNACE_SIDE
    ]
  },
  [Block.CHEST]: {
    id: Block.CHEST,
    name: 'Chest',
    solid: true,
    transparent: false,
    hardness: 2.5,
    dropId: Block.CHEST,
    soundType: 'wood',
    textures: [
      TextureIndex.CHEST_SIDE,
      TextureIndex.CHEST_SIDE,
      TextureIndex.CHEST_TOP,
      TextureIndex.CHEST_TOP,
      TextureIndex.CHEST_FRONT,
      TextureIndex.CHEST_SIDE
    ]
  },
  [Block.BRICKS]: {
    id: Block.BRICKS,
    name: 'Bricks',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.BRICKS,
    soundType: 'stone',
    textures: [TextureIndex.BRICKS, TextureIndex.BRICKS, TextureIndex.BRICKS, TextureIndex.BRICKS, TextureIndex.BRICKS, TextureIndex.BRICKS]
  },
  [Block.BOOKSHELF]: {
    id: Block.BOOKSHELF,
    name: 'Bookshelf',
    solid: true,
    transparent: false,
    hardness: 1.5,
    dropId: Block.BOOKSHELF,
    soundType: 'wood',
    textures: [
      TextureIndex.BOOKSHELF,
      TextureIndex.BOOKSHELF,
      TextureIndex.OAK_PLANKS,
      TextureIndex.OAK_PLANKS,
      TextureIndex.BOOKSHELF,
      TextureIndex.BOOKSHELF
    ]
  },
  [Block.TNT]: {
    id: Block.TNT,
    name: 'TNT',
    solid: true,
    transparent: false,
    hardness: 0.0,
    dropId: Block.TNT,
    soundType: 'grass',
    textures: [
      TextureIndex.TNT_SIDE,
      TextureIndex.TNT_SIDE,
      TextureIndex.TNT_TOP,
      TextureIndex.TNT_BOTTOM,
      TextureIndex.TNT_SIDE,
      TextureIndex.TNT_SIDE
    ]
  },
  [Block.TORCH]: {
    id: Block.TORCH,
    name: 'Torch',
    solid: false,
    transparent: true,
    luminance: 14,
    hardness: 0.0,
    dropId: Block.TORCH,
    soundType: 'wood',
    textures: [TextureIndex.TORCH, TextureIndex.TORCH, TextureIndex.TORCH, TextureIndex.TORCH, TextureIndex.TORCH, TextureIndex.TORCH]
  },
  [Block.DANDELION]: {
    id: Block.DANDELION,
    name: 'Dandelion',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.DANDELION,
    soundType: 'grass',
    textures: [TextureIndex.DANDELION, TextureIndex.DANDELION, TextureIndex.DANDELION, TextureIndex.DANDELION, TextureIndex.DANDELION, TextureIndex.DANDELION]
  },
  [Block.POPPY]: {
    id: Block.POPPY,
    name: 'Poppy',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.POPPY,
    soundType: 'grass',
    textures: [TextureIndex.POPPY, TextureIndex.POPPY, TextureIndex.POPPY, TextureIndex.POPPY, TextureIndex.POPPY, TextureIndex.POPPY]
  },
  [Block.SNOW]: {
    id: Block.SNOW,
    name: 'Snow Block',
    solid: true,
    transparent: false,
    hardness: 0.3,
    dropId: Block.SNOW,
    soundType: 'sand',
    textures: [TextureIndex.SNOW, TextureIndex.SNOW, TextureIndex.SNOW, TextureIndex.SNOW, TextureIndex.SNOW, TextureIndex.SNOW]
  },
  [Block.CACTUS]: {
    id: Block.CACTUS,
    name: 'Cactus',
    solid: true,
    transparent: false,
    hardness: 0.4,
    dropId: Block.CACTUS,
    soundType: 'wood',
    textures: [
      TextureIndex.CACTUS_SIDE,
      TextureIndex.CACTUS_SIDE,
      TextureIndex.CACTUS_TOP,
      TextureIndex.CACTUS_TOP,
      TextureIndex.CACTUS_SIDE,
      TextureIndex.CACTUS_SIDE
    ]
  },
  [Block.WHEAT_CROP]: {
    id: Block.WHEAT_CROP,
    name: 'Wheat Crop',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: ItemId.WHEAT,
    soundType: 'grass',
    textures: [
      TextureIndex.WHEAT_CROP,
      TextureIndex.WHEAT_CROP,
      TextureIndex.WHEAT_CROP,
      TextureIndex.WHEAT_CROP,
      TextureIndex.WHEAT_CROP,
      TextureIndex.WHEAT_CROP
    ]
  },
  [Block.BED]: {
    id: Block.BED,
    name: 'Bed',
    solid: true,
    transparent: false,
    hardness: 0.2,
    dropId: Block.BED,
    soundType: 'wood',
    textures: [
      TextureIndex.BED_SIDE,
      TextureIndex.BED_SIDE,
      TextureIndex.BED_TOP,
      TextureIndex.OAK_PLANKS,
      TextureIndex.BED_SIDE,
      TextureIndex.BED_SIDE
    ]
  },
  [Block.OBSIDIAN]: {
    id: Block.OBSIDIAN,
    name: 'Obsidian',
    solid: true,
    transparent: false,
    hardness: 15.0,
    dropId: Block.OBSIDIAN,
    soundType: 'stone',
    textures: [
      TextureIndex.OBSIDIAN,
      TextureIndex.OBSIDIAN,
      TextureIndex.OBSIDIAN,
      TextureIndex.OBSIDIAN,
      TextureIndex.OBSIDIAN,
      TextureIndex.OBSIDIAN
    ]
  },
  [Block.PORTAL]: {
    id: Block.PORTAL,
    name: 'Nether Portal',
    solid: false,
    transparent: true,
    hardness: 0.0,
    luminance: 11,
    soundType: 'glass',
    textures: [
      TextureIndex.PORTAL,
      TextureIndex.PORTAL,
      TextureIndex.PORTAL,
      TextureIndex.PORTAL,
      TextureIndex.PORTAL,
      TextureIndex.PORTAL
    ]
  },
  [Block.NETHERRACK]: {
    id: Block.NETHERRACK,
    name: 'Netherrack',
    solid: true,
    transparent: false,
    hardness: 0.4,
    dropId: Block.NETHERRACK,
    soundType: 'stone',
    textures: [
      TextureIndex.NETHERRACK,
      TextureIndex.NETHERRACK,
      TextureIndex.NETHERRACK,
      TextureIndex.NETHERRACK,
      TextureIndex.NETHERRACK,
      TextureIndex.NETHERRACK
    ]
  },
  [Block.SOUL_SAND]: {
    id: Block.SOUL_SAND,
    name: 'Soul Sand',
    solid: true,
    transparent: false,
    hardness: 0.5,
    dropId: Block.SOUL_SAND,
    soundType: 'sand',
    textures: [
      TextureIndex.SOUL_SAND,
      TextureIndex.SOUL_SAND,
      TextureIndex.SOUL_SAND,
      TextureIndex.SOUL_SAND,
      TextureIndex.SOUL_SAND,
      TextureIndex.SOUL_SAND
    ]
  },
  [Block.GLOWSTONE]: {
    id: Block.GLOWSTONE,
    name: 'Glowstone',
    solid: true,
    transparent: false,
    hardness: 0.3,
    luminance: 15,
    dropId: ItemId.GLOWSTONE_DUST,
    soundType: 'glass',
    textures: [
      TextureIndex.GLOWSTONE,
      TextureIndex.GLOWSTONE,
      TextureIndex.GLOWSTONE,
      TextureIndex.GLOWSTONE,
      TextureIndex.GLOWSTONE,
      TextureIndex.GLOWSTONE
    ]
  },
  [Block.NETHER_BRICKS]: {
    id: Block.NETHER_BRICKS,
    name: 'Nether Bricks',
    solid: true,
    transparent: false,
    hardness: 2.0,
    dropId: Block.NETHER_BRICKS,
    soundType: 'stone',
    textures: [
      TextureIndex.NETHER_BRICKS,
      TextureIndex.NETHER_BRICKS,
      TextureIndex.NETHER_BRICKS,
      TextureIndex.NETHER_BRICKS,
      TextureIndex.NETHER_BRICKS,
      TextureIndex.NETHER_BRICKS
    ]
  },
  [Block.NETHER_QUARTZ_ORE]: {
    id: Block.NETHER_QUARTZ_ORE,
    name: 'Nether Quartz Ore',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: ItemId.QUARTZ,
    soundType: 'stone',
    textures: [
      TextureIndex.NETHER_QUARTZ_ORE,
      TextureIndex.NETHER_QUARTZ_ORE,
      TextureIndex.NETHER_QUARTZ_ORE,
      TextureIndex.NETHER_QUARTZ_ORE,
      TextureIndex.NETHER_QUARTZ_ORE,
      TextureIndex.NETHER_QUARTZ_ORE
    ]
  },
  [Block.LAVA]: {
    id: Block.LAVA,
    name: 'Lava',
    solid: false,
    transparent: true,
    hardness: 100.0,
    luminance: 15,
    soundType: 'stone',
    textures: [
      TextureIndex.LAVA,
      TextureIndex.LAVA,
      TextureIndex.LAVA,
      TextureIndex.LAVA,
      TextureIndex.LAVA,
      TextureIndex.LAVA
    ]
  },
  [Block.ENCHANTING_TABLE]: {
    id: Block.ENCHANTING_TABLE,
    name: 'Enchanting Table',
    solid: true,
    transparent: false,
    hardness: 5.0,
    dropId: Block.ENCHANTING_TABLE,
    luminance: 7,
    soundType: 'stone',
    textures: [
      TextureIndex.ENCHANTING_TABLE_SIDE,
      TextureIndex.ENCHANTING_TABLE_SIDE,
      TextureIndex.ENCHANTING_TABLE_TOP,
      TextureIndex.ENCHANTING_TABLE_BOTTOM,
      TextureIndex.ENCHANTING_TABLE_SIDE,
      TextureIndex.ENCHANTING_TABLE_SIDE
    ]
  },
  [Block.BREWING_STAND]: {
    id: Block.BREWING_STAND,
    name: 'Brewing Stand',
    solid: true,
    transparent: true,
    hardness: 0.8,
    dropId: Block.BREWING_STAND,
    soundType: 'stone',
    textures: [
      TextureIndex.BREWING_STAND_SIDE,
      TextureIndex.BREWING_STAND_SIDE,
      TextureIndex.BREWING_STAND_TOP,
      TextureIndex.BREWING_STAND_SIDE,
      TextureIndex.BREWING_STAND_SIDE,
      TextureIndex.BREWING_STAND_SIDE
    ]
  },
  [Block.NETHER_WART_BLOCK]: {
    id: Block.NETHER_WART_BLOCK,
    name: 'Nether Wart Block',
    solid: true,
    transparent: false,
    hardness: 0.7,
    dropId: ItemId.NETHER_WART,
    soundType: 'wood',
    textures: [
      TextureIndex.NETHER_WART_BLOCK,
      TextureIndex.NETHER_WART_BLOCK,
      TextureIndex.NETHER_WART_BLOCK,
      TextureIndex.NETHER_WART_BLOCK,
      TextureIndex.NETHER_WART_BLOCK,
      TextureIndex.NETHER_WART_BLOCK
    ]
  },
  [Block.CORAL_BRAIN]: {
    id: Block.CORAL_BRAIN,
    name: 'Brain Coral Block',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.CORAL_BRAIN,
    soundType: 'stone',
    textures: [TextureIndex.CORAL_BRAIN, TextureIndex.CORAL_BRAIN, TextureIndex.CORAL_BRAIN, TextureIndex.CORAL_BRAIN, TextureIndex.CORAL_BRAIN, TextureIndex.CORAL_BRAIN]
  },
  [Block.CORAL_BUBBLE]: {
    id: Block.CORAL_BUBBLE,
    name: 'Bubble Coral Block',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.CORAL_BUBBLE,
    soundType: 'stone',
    textures: [TextureIndex.CORAL_BUBBLE, TextureIndex.CORAL_BUBBLE, TextureIndex.CORAL_BUBBLE, TextureIndex.CORAL_BUBBLE, TextureIndex.CORAL_BUBBLE, TextureIndex.CORAL_BUBBLE]
  },
  [Block.CORAL_FIRE]: {
    id: Block.CORAL_FIRE,
    name: 'Fire Coral Block',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.CORAL_FIRE,
    soundType: 'stone',
    textures: [TextureIndex.CORAL_FIRE, TextureIndex.CORAL_FIRE, TextureIndex.CORAL_FIRE, TextureIndex.CORAL_FIRE, TextureIndex.CORAL_FIRE, TextureIndex.CORAL_FIRE]
  },
  [Block.CORAL_HORN]: {
    id: Block.CORAL_HORN,
    name: 'Horn Coral Block',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.CORAL_HORN,
    soundType: 'stone',
    textures: [TextureIndex.CORAL_HORN, TextureIndex.CORAL_HORN, TextureIndex.CORAL_HORN, TextureIndex.CORAL_HORN, TextureIndex.CORAL_HORN, TextureIndex.CORAL_HORN]
  },
  [Block.CORAL_TUBE]: {
    id: Block.CORAL_TUBE,
    name: 'Tube Coral Block',
    solid: true,
    transparent: false,
    hardness: 0.8,
    dropId: Block.CORAL_TUBE,
    soundType: 'stone',
    textures: [TextureIndex.CORAL_TUBE, TextureIndex.CORAL_TUBE, TextureIndex.CORAL_TUBE, TextureIndex.CORAL_TUBE, TextureIndex.CORAL_TUBE, TextureIndex.CORAL_TUBE]
  },
  [Block.SEAGRASS]: {
    id: Block.SEAGRASS,
    name: 'Seagrass',
    solid: false,
    transparent: true,
    hardness: 0.1,
    dropId: Block.SEAGRASS,
    soundType: 'grass',
    textures: [TextureIndex.SEAGRASS, TextureIndex.SEAGRASS, TextureIndex.SEAGRASS, TextureIndex.SEAGRASS, TextureIndex.SEAGRASS, TextureIndex.SEAGRASS]
  },
  [Block.KELP]: {
    id: Block.KELP,
    name: 'Kelp',
    solid: false,
    transparent: true,
    hardness: 0.1,
    dropId: Block.KELP,
    soundType: 'grass',
    textures: [TextureIndex.KELP_STEM, TextureIndex.KELP_STEM, TextureIndex.KELP_TOP, TextureIndex.KELP_STEM, TextureIndex.KELP_STEM, TextureIndex.KELP_STEM]
  },
  [Block.SEA_LANTERN]: {
    id: Block.SEA_LANTERN,
    name: 'Sea Lantern',
    solid: true,
    transparent: false,
    hardness: 0.3,
    luminance: 15,
    dropId: Block.SEA_LANTERN,
    soundType: 'glass',
    textures: [TextureIndex.SEA_LANTERN, TextureIndex.SEA_LANTERN, TextureIndex.SEA_LANTERN, TextureIndex.SEA_LANTERN, TextureIndex.SEA_LANTERN, TextureIndex.SEA_LANTERN]
  },
  [Block.REDSTONE_WIRE]: {
    id: Block.REDSTONE_WIRE,
    name: 'Redstone Wire',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: ItemId.REDSTONE_DUST,
    soundType: 'stone',
    textures: [TextureIndex.REDSTONE_WIRE, TextureIndex.REDSTONE_WIRE, TextureIndex.REDSTONE_WIRE, TextureIndex.REDSTONE_WIRE, TextureIndex.REDSTONE_WIRE, TextureIndex.REDSTONE_WIRE]
  },
  [Block.REDSTONE_TORCH]: {
    id: Block.REDSTONE_TORCH,
    name: 'Redstone Torch',
    solid: false,
    transparent: true,
    hardness: 0.0,
    luminance: 7,
    dropId: Block.REDSTONE_TORCH,
    soundType: 'wood',
    textures: [TextureIndex.REDSTONE_TORCH, TextureIndex.REDSTONE_TORCH, TextureIndex.REDSTONE_TORCH, TextureIndex.REDSTONE_TORCH, TextureIndex.REDSTONE_TORCH, TextureIndex.REDSTONE_TORCH]
  },
  [Block.LEVER]: {
    id: Block.LEVER,
    name: 'Lever',
    solid: false,
    transparent: true,
    hardness: 0.5,
    dropId: Block.LEVER,
    soundType: 'wood',
    textures: [TextureIndex.LEVER, TextureIndex.LEVER, TextureIndex.LEVER, TextureIndex.LEVER, TextureIndex.LEVER, TextureIndex.LEVER]
  },
  [Block.REDSTONE_LAMP]: {
    id: Block.REDSTONE_LAMP,
    name: 'Redstone Lamp',
    solid: true,
    transparent: false,
    hardness: 0.3,
    dropId: Block.REDSTONE_LAMP,
    soundType: 'glass',
    textures: [TextureIndex.REDSTONE_LAMP, TextureIndex.REDSTONE_LAMP, TextureIndex.REDSTONE_LAMP, TextureIndex.REDSTONE_LAMP, TextureIndex.REDSTONE_LAMP, TextureIndex.REDSTONE_LAMP]
  },
  [Block.REDSTONE_LAMP_LIT]: {
    id: Block.REDSTONE_LAMP_LIT,
    name: 'Redstone Lamp (Lit)',
    solid: true,
    transparent: false,
    hardness: 0.3,
    luminance: 15,
    dropId: Block.REDSTONE_LAMP,
    soundType: 'glass',
    textures: [TextureIndex.REDSTONE_LAMP_LIT, TextureIndex.REDSTONE_LAMP_LIT, TextureIndex.REDSTONE_LAMP_LIT, TextureIndex.REDSTONE_LAMP_LIT, TextureIndex.REDSTONE_LAMP_LIT, TextureIndex.REDSTONE_LAMP_LIT]
  },
  [Block.FARMLAND]: {
    id: Block.FARMLAND,
    name: 'Farmland',
    solid: true,
    transparent: false,
    hardness: 0.6,
    dropId: Block.DIRT,
    soundType: 'gravel',
    textures: [TextureIndex.FARMLAND_SIDE, TextureIndex.FARMLAND_SIDE, TextureIndex.FARMLAND_TOP, TextureIndex.DIRT, TextureIndex.FARMLAND_SIDE, TextureIndex.FARMLAND_SIDE]
  },
  [Block.COBWEB]: {
    id: Block.COBWEB,
    name: 'Cobweb',
    solid: false,
    transparent: true,
    hardness: 4.0,
    dropId: Block.COBWEB,
    soundType: 'stone',
    textures: [TextureIndex.COBWEB, TextureIndex.COBWEB, TextureIndex.COBWEB, TextureIndex.COBWEB, TextureIndex.COBWEB, TextureIndex.COBWEB]
  },
  [Block.RAIL]: {
    id: Block.RAIL,
    name: 'Rail',
    solid: false,
    transparent: true,
    hardness: 0.7,
    dropId: Block.RAIL,
    soundType: 'stone',
    textures: [TextureIndex.RAIL, TextureIndex.RAIL, TextureIndex.RAIL, TextureIndex.RAIL, TextureIndex.RAIL, TextureIndex.RAIL]
  },
  [Block.SUGAR_CANE]: {
    id: Block.SUGAR_CANE,
    name: 'Sugar Cane',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.SUGAR_CANE,
    soundType: 'grass',
    textures: [TextureIndex.SUGAR_CANE, TextureIndex.SUGAR_CANE, TextureIndex.SUGAR_CANE, TextureIndex.SUGAR_CANE, TextureIndex.SUGAR_CANE, TextureIndex.SUGAR_CANE]
  },
  [Block.RED_MUSHROOM]: {
    id: Block.RED_MUSHROOM,
    name: 'Red Mushroom',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.RED_MUSHROOM,
    soundType: 'grass',
    luminance: 1,
    textures: [TextureIndex.RED_MUSHROOM, TextureIndex.RED_MUSHROOM, TextureIndex.RED_MUSHROOM, TextureIndex.RED_MUSHROOM, TextureIndex.RED_MUSHROOM, TextureIndex.RED_MUSHROOM]
  },
  [Block.BROWN_MUSHROOM]: {
    id: Block.BROWN_MUSHROOM,
    name: 'Brown Mushroom',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.BROWN_MUSHROOM,
    soundType: 'grass',
    luminance: 1,
    textures: [TextureIndex.BROWN_MUSHROOM, TextureIndex.BROWN_MUSHROOM, TextureIndex.BROWN_MUSHROOM, TextureIndex.BROWN_MUSHROOM, TextureIndex.BROWN_MUSHROOM, TextureIndex.BROWN_MUSHROOM]
  },
  [Block.LILY_PAD]: {
    id: Block.LILY_PAD,
    name: 'Lily Pad',
    solid: false,
    transparent: true,
    hardness: 0.0,
    dropId: Block.LILY_PAD,
    soundType: 'grass',
    textures: [TextureIndex.LILY_PAD, TextureIndex.LILY_PAD, TextureIndex.LILY_PAD, TextureIndex.LILY_PAD, TextureIndex.LILY_PAD, TextureIndex.LILY_PAD]
  },
  [Block.OAK_FENCE]: {
    id: Block.OAK_FENCE,
    name: 'Oak Fence',
    solid: true,
    transparent: true,
    hardness: 2.0,
    dropId: Block.OAK_FENCE,
    soundType: 'wood',
    textures: [TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS, TextureIndex.OAK_PLANKS]
  },
  [Block.DRIPSTONE_BLOCK]: {
    id: Block.DRIPSTONE_BLOCK,
    name: 'Dripstone Block',
    solid: true,
    transparent: false,
    hardness: 1.5,
    dropId: Block.DRIPSTONE_BLOCK,
    soundType: 'stone',
    textures: [TextureIndex.DRIPSTONE_BLOCK, TextureIndex.DRIPSTONE_BLOCK, TextureIndex.DRIPSTONE_BLOCK, TextureIndex.DRIPSTONE_BLOCK, TextureIndex.DRIPSTONE_BLOCK, TextureIndex.DRIPSTONE_BLOCK]
  },
  [Block.ICE]: {
    id: Block.ICE,
    name: 'Ice',
    solid: true,
    transparent: true,
    hardness: 0.5,
    dropId: Block.AIR,
    soundType: 'glass',
    textures: [TextureIndex.ICE, TextureIndex.ICE, TextureIndex.ICE, TextureIndex.ICE, TextureIndex.ICE, TextureIndex.ICE]
  },
  [Block.NETHER_BRICK_FENCE]: {
    id: Block.NETHER_BRICK_FENCE,
    name: 'Nether Brick Fence',
    solid: true,
    transparent: true,
    hardness: 2.0,
    dropId: Block.NETHER_BRICK_FENCE,
    soundType: 'stone',
    textures: [TextureIndex.NETHER_BRICKS, TextureIndex.NETHER_BRICKS, TextureIndex.NETHER_BRICKS, TextureIndex.NETHER_BRICKS, TextureIndex.NETHER_BRICKS, TextureIndex.NETHER_BRICKS]
  },
  [Block.SPAWNER]: {
    id: Block.SPAWNER,
    name: 'Monster Spawner',
    solid: true,
    transparent: true,
    hardness: 5.0,
    luminance: 3,
    dropId: Block.AIR,
    soundType: 'stone',
    textures: [TextureIndex.SPAWNER, TextureIndex.SPAWNER, TextureIndex.SPAWNER, TextureIndex.SPAWNER, TextureIndex.SPAWNER, TextureIndex.SPAWNER]
  },
  [Block.END_STONE]: {
    id: Block.END_STONE,
    name: 'End Stone',
    solid: true,
    transparent: false,
    hardness: 3.0,
    dropId: Block.END_STONE,
    soundType: 'stone',
    textures: [TextureIndex.END_STONE, TextureIndex.END_STONE, TextureIndex.END_STONE, TextureIndex.END_STONE, TextureIndex.END_STONE, TextureIndex.END_STONE]
  },
  [Block.END_PORTAL_FRAME]: {
    id: Block.END_PORTAL_FRAME,
    name: 'End Portal Frame',
    solid: true,
    transparent: false,
    hardness: 100.0,
    dropId: Block.END_PORTAL_FRAME,
    soundType: 'stone',
    textures: [
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_TOP,
      TextureIndex.END_STONE,
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_SIDE
    ]
  },
  [Block.END_PORTAL_FRAME_FILLED]: {
    id: Block.END_PORTAL_FRAME_FILLED,
    name: 'End Portal Frame (Active)',
    solid: true,
    transparent: false,
    hardness: 100.0,
    luminance: 1,
    dropId: Block.END_PORTAL_FRAME,
    soundType: 'stone',
    textures: [
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_FILLED_TOP,
      TextureIndex.END_STONE,
      TextureIndex.END_PORTAL_FRAME_SIDE,
      TextureIndex.END_PORTAL_FRAME_SIDE
    ]
  },
  [Block.END_PORTAL]: {
    id: Block.END_PORTAL,
    name: 'End Portal',
    solid: false,
    transparent: true,
    hardness: 100.0,
    luminance: 15,
    soundType: 'glass',
    textures: [TextureIndex.END_PORTAL, TextureIndex.END_PORTAL, TextureIndex.END_PORTAL, TextureIndex.END_PORTAL, TextureIndex.END_PORTAL, TextureIndex.END_PORTAL]
  },
  [Block.END_CRYSTAL]: {
    id: Block.END_CRYSTAL,
    name: 'End Crystal',
    solid: false,
    transparent: true,
    hardness: 0.1,
    luminance: 10,
    dropId: Block.AIR,
    soundType: 'glass',
    textures: [TextureIndex.END_CRYSTAL, TextureIndex.END_CRYSTAL, TextureIndex.END_CRYSTAL, TextureIndex.END_CRYSTAL, TextureIndex.END_CRYSTAL, TextureIndex.END_CRYSTAL]
  }
};

export const ITEM_DEFS: Record<number, ItemDef> = {
  [ItemId.STICK]: { id: ItemId.STICK, name: 'Stick', isBlock: false, maxStack: 64 },
  [ItemId.WOODEN_PICKAXE]: { id: ItemId.WOODEN_PICKAXE, name: 'Wooden Pickaxe', isBlock: false, maxStack: 1, toolType: 'pickaxe', toolTier: 1, miningSpeedMultiplier: 2, maxDurability: 59 },
  [ItemId.STONE_PICKAXE]: { id: ItemId.STONE_PICKAXE, name: 'Stone Pickaxe', isBlock: false, maxStack: 1, toolType: 'pickaxe', toolTier: 2, miningSpeedMultiplier: 4, maxDurability: 131 },
  [ItemId.IRON_PICKAXE]: { id: ItemId.IRON_PICKAXE, name: 'Iron Pickaxe', isBlock: false, maxStack: 1, toolType: 'pickaxe', toolTier: 3, miningSpeedMultiplier: 6, maxDurability: 250 },
  [ItemId.DIAMOND_PICKAXE]: { id: ItemId.DIAMOND_PICKAXE, name: 'Diamond Pickaxe', isBlock: false, maxStack: 1, toolType: 'pickaxe', toolTier: 4, miningSpeedMultiplier: 8, maxDurability: 1561 },
  [ItemId.WOODEN_SWORD]: { id: ItemId.WOODEN_SWORD, name: 'Wooden Sword', isBlock: false, maxStack: 1, toolType: 'sword', toolTier: 1, maxDurability: 59 },
  [ItemId.STONE_SWORD]: { id: ItemId.STONE_SWORD, name: 'Stone Sword', isBlock: false, maxStack: 1, toolType: 'sword', toolTier: 2, maxDurability: 131 },
  [ItemId.IRON_SWORD]: { id: ItemId.IRON_SWORD, name: 'Iron Sword', isBlock: false, maxStack: 1, toolType: 'sword', toolTier: 3, maxDurability: 250 },
  [ItemId.DIAMOND_SWORD]: { id: ItemId.DIAMOND_SWORD, name: 'Diamond Sword', isBlock: false, maxStack: 1, toolType: 'sword', toolTier: 4, maxDurability: 1561 },
  [ItemId.WOODEN_AXE]: { id: ItemId.WOODEN_AXE, name: 'Wooden Axe', isBlock: false, maxStack: 1, toolType: 'axe', toolTier: 1, miningSpeedMultiplier: 2, maxDurability: 59 },
  [ItemId.STONE_AXE]: { id: ItemId.STONE_AXE, name: 'Stone Axe', isBlock: false, maxStack: 1, toolType: 'axe', toolTier: 2, miningSpeedMultiplier: 4, maxDurability: 131 },
  [ItemId.IRON_AXE]: { id: ItemId.IRON_AXE, name: 'Iron Axe', isBlock: false, maxStack: 1, toolType: 'axe', toolTier: 3, miningSpeedMultiplier: 6, maxDurability: 250 },
  [ItemId.DIAMOND_AXE]: { id: ItemId.DIAMOND_AXE, name: 'Diamond Axe', isBlock: false, maxStack: 1, toolType: 'axe', toolTier: 4, miningSpeedMultiplier: 8, maxDurability: 1561 },
  [ItemId.WOODEN_SHOVEL]: { id: ItemId.WOODEN_SHOVEL, name: 'Wooden Shovel', isBlock: false, maxStack: 1, toolType: 'shovel', toolTier: 1, miningSpeedMultiplier: 2, maxDurability: 59 },
  [ItemId.STONE_SHOVEL]: { id: ItemId.STONE_SHOVEL, name: 'Stone Shovel', isBlock: false, maxStack: 1, toolType: 'shovel', toolTier: 2, miningSpeedMultiplier: 4, maxDurability: 131 },
  [ItemId.IRON_SHOVEL]: { id: ItemId.IRON_SHOVEL, name: 'Iron Shovel', isBlock: false, maxStack: 1, toolType: 'shovel', toolTier: 3, miningSpeedMultiplier: 6, maxDurability: 250 },
  [ItemId.DIAMOND_SHOVEL]: { id: ItemId.DIAMOND_SHOVEL, name: 'Diamond Shovel', isBlock: false, maxStack: 1, toolType: 'shovel', toolTier: 4, miningSpeedMultiplier: 8, maxDurability: 1561 },
  [ItemId.COAL]: { id: ItemId.COAL, name: 'Coal', isBlock: false, maxStack: 64 },
  [ItemId.IRON_INGOT]: { id: ItemId.IRON_INGOT, name: 'Iron Ingot', isBlock: false, maxStack: 64 },
  [ItemId.GOLD_INGOT]: { id: ItemId.GOLD_INGOT, name: 'Gold Ingot', isBlock: false, maxStack: 64 },
  [ItemId.DIAMOND]: { id: ItemId.DIAMOND, name: 'Diamond', isBlock: false, maxStack: 64 },
  [ItemId.APPLE]: { id: ItemId.APPLE, name: 'Apple', isBlock: false, maxStack: 64 },
  [ItemId.EMERALD]: { id: ItemId.EMERALD, name: 'Emerald', isBlock: false, maxStack: 64 },
  [ItemId.BREAD]: { id: ItemId.BREAD, name: 'Bread', isBlock: false, maxStack: 64 },
  [ItemId.RAW_BEEF]: { id: ItemId.RAW_BEEF, name: 'Raw Beef', isBlock: false, maxStack: 64 },
  [ItemId.COOKED_BEEF]: { id: ItemId.COOKED_BEEF, name: 'Steak', isBlock: false, maxStack: 64 },
  [ItemId.PORKCHOP]: { id: ItemId.PORKCHOP, name: 'Raw Porkchop', isBlock: false, maxStack: 64 },
  [ItemId.FEATHER]: { id: ItemId.FEATHER, name: 'Feather', isBlock: false, maxStack: 64 },
  [ItemId.RAW_CHICKEN]: { id: ItemId.RAW_CHICKEN, name: 'Raw Chicken', isBlock: false, maxStack: 64 },
  [ItemId.LEATHER]: { id: ItemId.LEATHER, name: 'Leather', isBlock: false, maxStack: 64 },
  [ItemId.GUNPOWDER]: { id: ItemId.GUNPOWDER, name: 'Gunpowder', isBlock: false, maxStack: 64 },
  [ItemId.ROTTEN_FLESH]: { id: ItemId.ROTTEN_FLESH, name: 'Rotten Flesh', isBlock: false, maxStack: 64 },
  [ItemId.WOOL]: { id: ItemId.WOOL, name: 'Wool', isBlock: false, maxStack: 64 },
  [ItemId.WHEAT]: { id: ItemId.WHEAT, name: 'Wheat', isBlock: false, maxStack: 64 },
  [ItemId.BOW]: { id: ItemId.BOW, name: 'Bow', isBlock: false, maxStack: 1, maxDurability: 384 },
  [ItemId.ARROW]: { id: ItemId.ARROW, name: 'Arrow', isBlock: false, maxStack: 64 },
  [ItemId.BONE]: { id: ItemId.BONE, name: 'Bone', isBlock: false, maxStack: 64 },
  [ItemId.FLINT]: { id: ItemId.FLINT, name: 'Flint', isBlock: false, maxStack: 64 },
  [ItemId.IRON_HELMET]: { id: ItemId.IRON_HELMET, name: 'Iron Helmet', isBlock: false, maxStack: 1, maxDurability: 165, armorSlot: 'helmet', defensePoints: 2 },
  [ItemId.IRON_CHESTPLATE]: { id: ItemId.IRON_CHESTPLATE, name: 'Iron Chestplate', isBlock: false, maxStack: 1, maxDurability: 240, armorSlot: 'chestplate', defensePoints: 6 },
  [ItemId.IRON_LEGGINGS]: { id: ItemId.IRON_LEGGINGS, name: 'Iron Leggings', isBlock: false, maxStack: 1, maxDurability: 225, armorSlot: 'leggings', defensePoints: 5 },
  [ItemId.IRON_BOOTS]: { id: ItemId.IRON_BOOTS, name: 'Iron Boots', isBlock: false, maxStack: 1, maxDurability: 195, armorSlot: 'boots', defensePoints: 2 },
  [ItemId.DIAMOND_HELMET]: { id: ItemId.DIAMOND_HELMET, name: 'Diamond Helmet', isBlock: false, maxStack: 1, maxDurability: 363, armorSlot: 'helmet', defensePoints: 3 },
  [ItemId.DIAMOND_CHESTPLATE]: { id: ItemId.DIAMOND_CHESTPLATE, name: 'Diamond Chestplate', isBlock: false, maxStack: 1, maxDurability: 528, armorSlot: 'chestplate', defensePoints: 8 },
  [ItemId.DIAMOND_LEGGINGS]: { id: ItemId.DIAMOND_LEGGINGS, name: 'Diamond Leggings', isBlock: false, maxStack: 1, maxDurability: 495, armorSlot: 'leggings', defensePoints: 6 },
  [ItemId.DIAMOND_BOOTS]: { id: ItemId.DIAMOND_BOOTS, name: 'Diamond Boots', isBlock: false, maxStack: 1, maxDurability: 429, armorSlot: 'boots', defensePoints: 3 },
  [ItemId.QUARTZ]: { id: ItemId.QUARTZ, name: 'Nether Quartz', isBlock: false, maxStack: 64 },
  [ItemId.GLOWSTONE_DUST]: { id: ItemId.GLOWSTONE_DUST, name: 'Glowstone Dust', isBlock: false, maxStack: 64 },
  [ItemId.BOOK]: { id: ItemId.BOOK, name: 'Book', isBlock: false, maxStack: 64 },
  [ItemId.GOLD_NUGGET]: { id: ItemId.GOLD_NUGGET, name: 'Gold Nugget', isBlock: false, maxStack: 64 },
  [ItemId.GHAST_TEAR]: { id: ItemId.GHAST_TEAR, name: 'Ghast Tear', isBlock: false, maxStack: 64 },
  [ItemId.BLAZE_ROD]: { id: ItemId.BLAZE_ROD, name: 'Blaze Rod', isBlock: false, maxStack: 64 },
  [ItemId.BLAZE_POWDER]: { id: ItemId.BLAZE_POWDER, name: 'Blaze Powder', isBlock: false, maxStack: 64 },
  [ItemId.NETHER_WART]: { id: ItemId.NETHER_WART, name: 'Nether Wart', isBlock: false, maxStack: 64 },
  [ItemId.GLASS_BOTTLE]: { id: ItemId.GLASS_BOTTLE, name: 'Glass Bottle', isBlock: false, maxStack: 64 },
  [ItemId.POTION_HEALING]: { id: ItemId.POTION_HEALING, name: 'Potion of Healing', isBlock: false, maxStack: 1 },
  [ItemId.POTION_SPEED]: { id: ItemId.POTION_SPEED, name: 'Potion of Speed', isBlock: false, maxStack: 1 },
  [ItemId.POTION_FIRE_RESISTANCE]: { id: ItemId.POTION_FIRE_RESISTANCE, name: 'Potion of Fire Resistance', isBlock: false, maxStack: 1 },
  [ItemId.POTION_NIGHT_VISION]: { id: ItemId.POTION_NIGHT_VISION, name: 'Potion of Night Vision', isBlock: false, maxStack: 1 },
  [ItemId.POTION_STRENGTH]: { id: ItemId.POTION_STRENGTH, name: 'Potion of Strength', isBlock: false, maxStack: 1 },
  [ItemId.RAW_FISH]: { id: ItemId.RAW_FISH, name: 'Raw Fish', isBlock: false, maxStack: 64 },
  [ItemId.COOKED_FISH]: { id: ItemId.COOKED_FISH, name: 'Cooked Fish', isBlock: false, maxStack: 64 },
  [ItemId.REDSTONE_DUST]: { id: ItemId.REDSTONE_DUST, name: 'Redstone Dust', isBlock: false, maxStack: 64 },
  [ItemId.LAPIS_LAZULI]: { id: ItemId.LAPIS_LAZULI, name: 'Lapis Lazuli', isBlock: false, maxStack: 64 },
  [ItemId.BUCKET]: { id: ItemId.BUCKET, name: 'Bucket', isBlock: false, maxStack: 16 },
  [ItemId.WATER_BUCKET]: { id: ItemId.WATER_BUCKET, name: 'Water Bucket', isBlock: false, maxStack: 1 },
  [ItemId.LAVA_BUCKET]: { id: ItemId.LAVA_BUCKET, name: 'Lava Bucket', isBlock: false, maxStack: 1 },
  [ItemId.MILK_BUCKET]: { id: ItemId.MILK_BUCKET, name: 'Milk Bucket', isBlock: false, maxStack: 1 },
  [ItemId.WHEAT_SEEDS]: { id: ItemId.WHEAT_SEEDS, name: 'Wheat Seeds', isBlock: false, maxStack: 64 },
  [ItemId.WOODEN_HOE]: { id: ItemId.WOODEN_HOE, name: 'Wooden Hoe', isBlock: false, maxStack: 1, toolType: 'hoe' as any, toolTier: 1, maxDurability: 59 },
  [ItemId.STONE_HOE]: { id: ItemId.STONE_HOE, name: 'Stone Hoe', isBlock: false, maxStack: 1, toolType: 'hoe' as any, toolTier: 2, maxDurability: 131 },
  [ItemId.IRON_HOE]: { id: ItemId.IRON_HOE, name: 'Iron Hoe', isBlock: false, maxStack: 1, toolType: 'hoe' as any, toolTier: 3, maxDurability: 250 },
  [ItemId.DIAMOND_HOE]: { id: ItemId.DIAMOND_HOE, name: 'Diamond Hoe', isBlock: false, maxStack: 1, toolType: 'hoe' as any, toolTier: 4, maxDurability: 1561 },
  [ItemId.BOAT]: { id: ItemId.BOAT, name: 'Oak Boat', isBlock: false, maxStack: 1 },
  [ItemId.MINECART]: { id: ItemId.MINECART, name: 'Minecart', isBlock: false, maxStack: 1 },
  [ItemId.ENDER_PEARL]: { id: ItemId.ENDER_PEARL, name: 'Ender Pearl', isBlock: false, maxStack: 16 },
  [ItemId.EYE_OF_ENDER]: { id: ItemId.EYE_OF_ENDER, name: 'Eye of Ender', isBlock: false, maxStack: 64 },
  [ItemId.LEATHER_HELMET]: { id: ItemId.LEATHER_HELMET, name: 'Leather Cap', isBlock: false, maxStack: 1, maxDurability: 55, armorSlot: 'helmet', defensePoints: 1 },
  [ItemId.LEATHER_CHESTPLATE]: { id: ItemId.LEATHER_CHESTPLATE, name: 'Leather Tunic', isBlock: false, maxStack: 1, maxDurability: 80, armorSlot: 'chestplate', defensePoints: 3 },
  [ItemId.LEATHER_LEGGINGS]: { id: ItemId.LEATHER_LEGGINGS, name: 'Leather Pants', isBlock: false, maxStack: 1, maxDurability: 75, armorSlot: 'leggings', defensePoints: 2 },
  [ItemId.LEATHER_BOOTS]: { id: ItemId.LEATHER_BOOTS, name: 'Leather Boots', isBlock: false, maxStack: 1, maxDurability: 65, armorSlot: 'boots', defensePoints: 1 },
  [ItemId.GOLDEN_HELMET]: { id: ItemId.GOLDEN_HELMET, name: 'Golden Helmet', isBlock: false, maxStack: 1, maxDurability: 77, armorSlot: 'helmet', defensePoints: 2 },
  [ItemId.GOLDEN_CHESTPLATE]: { id: ItemId.GOLDEN_CHESTPLATE, name: 'Golden Chestplate', isBlock: false, maxStack: 1, maxDurability: 112, armorSlot: 'chestplate', defensePoints: 5 },
  [ItemId.GOLDEN_LEGGINGS]: { id: ItemId.GOLDEN_LEGGINGS, name: 'Golden Leggings', isBlock: false, maxStack: 1, maxDurability: 105, armorSlot: 'leggings', defensePoints: 3 },
  [ItemId.GOLDEN_BOOTS]: { id: ItemId.GOLDEN_BOOTS, name: 'Golden Boots', isBlock: false, maxStack: 1, maxDurability: 91, armorSlot: 'boots', defensePoints: 1 },
  [ItemId.NETHERITE_HELMET]: { id: ItemId.NETHERITE_HELMET, name: 'Netherite Helmet', isBlock: false, maxStack: 1, maxDurability: 407, armorSlot: 'helmet', defensePoints: 3 },
  [ItemId.NETHERITE_CHESTPLATE]: { id: ItemId.NETHERITE_CHESTPLATE, name: 'Netherite Chestplate', isBlock: false, maxStack: 1, maxDurability: 592, armorSlot: 'chestplate', defensePoints: 8 },
  [ItemId.NETHERITE_LEGGINGS]: { id: ItemId.NETHERITE_LEGGINGS, name: 'Netherite Leggings', isBlock: false, maxStack: 1, maxDurability: 555, armorSlot: 'leggings', defensePoints: 6 },
  [ItemId.NETHERITE_BOOTS]: { id: ItemId.NETHERITE_BOOTS, name: 'Netherite Boots', isBlock: false, maxStack: 1, maxDurability: 481, armorSlot: 'boots', defensePoints: 3 },
  [ItemId.NETHERITE_INGOT]: { id: ItemId.NETHERITE_INGOT, name: 'Netherite Ingot', isBlock: false, maxStack: 64 }
};

export function getItemName(id: number): string {
  if (BLOCK_DEFS[id]) return BLOCK_DEFS[id].name;
  if (ITEM_DEFS[id]) return ITEM_DEFS[id].name;
  return 'Unknown Item';
}

export function isBlockItem(id: number): boolean {
  return id in BLOCK_DEFS && id !== Block.AIR;
}
